# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='catches',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='endurance_time',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
