# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 21:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20170107_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_happened',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='when record was juggled'),
        ),
        migrations.AlterField(
            model_name='record',
            name='url_to_proof',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recordcategory',
            name='pattern',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='info_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
