# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 21:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20170108_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_happened',
            field=models.DateField(default=datetime.date.today, verbose_name='when record was juggled'),
        ),
    ]
