# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-20 23:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20170108_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordcategory',
            name='record_type',
            field=models.CharField(choices=[('ALL_TYPES', 'all'), ('ENDURANCE', 'plain endurance'), ('TRICK', 'trick endurance'), ('CONSTRAIN', 'constrained')], default='ALL_TYPES', max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='catches',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name=' catches'),
        ),
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.RecordCategory', verbose_name=' record'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_happened',
            field=models.DateField(default=datetime.date.today, verbose_name=' date'),
        ),
        migrations.AlterField(
            model_name='record',
            name='url_to_proof',
            field=models.URLField(blank=True, null=True, verbose_name=' video/evidence url'),
        ),
        migrations.AlterField(
            model_name='recordcategory',
            name='prop',
            field=models.CharField(choices=[('ALL_PROPS', 'All'), ('BALLS', 'Balls'), ('BBALLS', 'Bouncing Balls'), ('CLUBS', 'Clubs'), ('RINGS', 'Rings')], default='BALLS', max_length=10),
        ),
    ]
